repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "2.2.1"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args:
          - --no-cache
      - id: poetry-install
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: sh -c 'poetry install -qn --no-root && poetry run mypy .'
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies:
          - poetry
